//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace daev5lr.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user09Entities1 : DbContext
    {
        public user09Entities1()
            : base("name=user09Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<climantTechModel> climantTechModel { get; set; }
        public virtual DbSet<climantTechType> climantTechType { get; set; }
        public virtual DbSet<comments> comments { get; set; }
        public virtual DbSet<requests> requests { get; set; }
        public virtual DbSet<requestStatus> requestStatus { get; set; }
        public virtual DbSet<type> type { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
