//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace daev5lr.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public requests()
        {
            this.comments = new HashSet<comments>();
        }
    
        public int RequestId { get; set; }
        public System.DateTime StartDate { get; set; }
        public int ClimateTechType { get; set; }
        public int ClimateTechModel { get; set; }
        public string ProblemDescryption { get; set; }
        public int RequestStatus { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string RepairParts { get; set; }
        public Nullable<int> MasterID { get; set; }
        public int ClientID { get; set; }
    
        public virtual climantTechModel climantTechModel { get; set; }
        public virtual climantTechType climantTechType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comments> comments { get; set; }
        public virtual requestStatus requestStatus1 { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
